name = "fortran-curl"
version = "0.4.0"
license = "ISC"
author = "Philipp Engel"
maintainer = "@interkosmos"
copyright = "Copyright (c) 2021, Philipp Engel"
description = "Fortran 2008 ISO C binding interfaces to libcurl"
keywords = ["curl", "libcurl", "http", "gopher", "smtp", "imap", "dict"]

[build]
link = "curl"

[[example]]
name = "dict"
source-dir = "examples/dict"
main = "dict.f90"

[[example]]
name = "download"
source-dir = "examples/download"
main = "download.f90"

[[example]]
name = "getinfo"
source-dir = "examples/getinfo"
main = "getinfo.f90"

[[example]]
name = "gopher"
source-dir = "examples/gopher"
main = "gopher.f90"

[[example]]
name = "http"
source-dir = "examples/http"
main = "http.f90"

[[example]]
name = "imap"
source-dir = "examples/imap"
main = "imap.f90"

[[example]]
name = "smtp"
source-dir = "examples/smtp"
main = "smtp.f90"

[[example]]
name = "post"
source-dir = "examples/post"
main = "post.f90"

[[example]]
name = "version"
source-dir = "examples/version"
main = "version.f90"
